kaniko-build:
  tags:
    - docker
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo $VERSION
    - mkdir -p /kaniko/.docker
    - cp "$USER_KEY" auth.json
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

    - /kaniko/executor
     --context $CI_PROJECT_DIR
     --dockerfile $CI_PROJECT_DIR/Dockerfile
     --destination $CI_REGISTRY_IMAGE:$VERSION
     --single-snapshot
     --cleanup

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - when: manual